version: 2

sources:
  - name: raw
    schema: gz_raw
    description: gz raw data sources
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez
        columns:
          - name: date_date
            description: "Date de la commande"
            tests:
              - unique
          - name: orders_id
            description: "Identifiant unique de la commande"
            tests:
              - unique
          - name: product_id
            description: "Identifiant unique du produit"
            tests:
              - unique
          - name: revenue
            description: "Chiffre d'affaires généré par la vente"
            tests:
              - unique
          - name: quantity
            description: "Nombre d'unités vendues"
            tests:
              - unique
      - name: products
        identifier: raw_gz_product
        description: purchase price by products
        columns:
          - name: product_id
            description: "identifiant produit"
            tests:
              - unique
              - not_null
          - name: purchase_id
            description: "identifiant achat"
            tests:
              - unique
              - not_null
      - name: ship
        identifier: raw_gz_ship
        description: push
        columns:
          - name: order_id
            description: Identifiant unique de la commande
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: Frais de livraison associés à la commande
            tests:
              - not_null
          - name: log_cost
            description: Coût de gestion du stockage des articles
            tests:
              - not_null
          - name: ship_cost
            description: Coût total du transport des produits
            tests:
              - not_null
