version: 2

sources:
  - name: raw
    schema: gz_raw
    description: gz raw data sources
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez
        columns:
          - name: date_date
            description: "Date de la commande"
          - name: orders_id
            description: "Identifiant unique de la commande"
          - name: pdt_id
            description: "Identifiant unique du produit"
          - name: revenue
            description: "Chiffre d'affaires généré par la vente"
          - name: quantity
            description: "Nombre d'unités vendues"
          - name: "(orders_id || '-' || pdt_id)"
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name: products
        identifier: raw_gz_product
        description: purchase price by products
        columns:
          - name: products_id
            description: "Identifiant produit"
            tests:
              - unique
              - not_null
          - name: purchase_id
            description: "Identifiant achat"
      - name: ship
        identifier: raw_gz_ship
        description: push
        columns:
          - name: orders_id
            description: "Identifiant unique de la commande"
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: "Frais de livraison associés à la commande"
          - name: log_cost
            description: "Coût de gestion du stockage des articles"
          - name: ship_cost
            description: "Coût total du transport des produits"
      - name: adwords
        identifier: raw_gz_adwords
        description: table adwords gz
        columns:
          - name: date_date
            description: "Date de la campagne publicitaire"

          - name: paid_source
            description: "Source payante de la campagne"

          - name: campaign_key
            description: "Identifiant unique de la campagne"

          - name: campgn_name
            description: "Nom de la campagne publicitaire"

          - name: adds_cost
            description: "Coût total des annonces"

          - name: impression
            description: "Nombre d'impressions générées"

          - name: click
            description: "Nombre de clics générés"
          
          - name: "(date_date || '-' || campaign_key)"
            description: primary key of the table
            tests:
              - unique
              - not_null

      - name: bing
        identifier: raw_gz_bing
        description: table bing gz
        columns:
          - name: date_date
            description: "Date de la campagne publicitaire"

          - name: paid_source
            description: "Source payante de la campagne"

          - name: campaign_key
            description: "Identifiant unique de la campagne"

          - name: camPGN_name
            description: "Nom de la campagne publicitaire"

          - name: adds_cost
            description: "Coût total des annonces"

          - name: impression
            description: "Nombre d'impressions générées"

          - name: click
            description: "Nombre de clics générés"

          - name: "(date_date || '-' || campaign_key)"
            description: primary key of the table
            tests:
              - unique
              - not_null

      - name: criteo
        identifier: raw_gz_criteo
        description: table criteo gz

        columns:
          - name: date_date
            description: "Date de la campagne publicitaire"

          - name: paid_source
            description: "Source payante de la campagne"

          - name: campaign_key
            description: "Identifiant unique de la campagne"

          - name: camPGN_name
            description: "Nom de la campagne publicitaire"

          - name: adds_cost
            description: "Coût total des annonces"

          - name: impression
            description: "Nombre d'impressions générées"

          - name: click
            description: "Nombre de clics générés"

          - name: "(date_date || '-' || campaign_key)"
            description: primary key of the table
            tests:
              - unique
              - not_null

      - name: facebook
        identifier: raw_gz_facebook
        description: table facebook gz

        columns:
          - name: date_date
            description: "Date de la campagne publicitaire"

          - name: paid_source
            description: "Source payante de la campagne"

          - name: campaign_key
            description: "Identifiant unique de la campagne"

          - name: camPGN_name
            description: "Nom de la campagne publicitaire"

          - name: adds_cost
            description: "Coût total des annonces"

          - name: impression
            description: "Nombre d'impressions générées"

          - name: click
            description: "Nombre de clics générés"
          - name: "(date_date || '-' || campaign_key)"
            description: primary key of the table
            tests:
              - unique
              - not_null
models:
  - name: int_sales_margin
    description: "Table intermédiaire pour calcul de la marge par vente"
  - name: int_order_margin
    description: "Table intermédiaire pour le calcul de la marge opérationnelle"
  - name: int_orders_operational
    description: "Table intermédiaire pour le calcul de la marge opérationnelle"
  - name: finance_days
    description: granularité quotidienne
  - name: int_campaigns
    description: "Table de campagne"
  - name: int_campaigns_day2
    description: "table de campagne par jour"
  - name: finance_campaigns_days
    description: "joint campagne et finance"
